import React, { createContext, useContext, useEffect, useMemo, useState } from 'react';

export type Language = 'ar' | 'en';

type TranslationKey = string;

type LanguageContextValue = {
  language: Language;
  direction: 'rtl' | 'ltr';
  setLanguage: (language: Language) => void;
  toggleLanguage: () => void;
  t: (key: TranslationKey, values?: Record<string, string | number>) => string;
};

const STORAGE_KEY = 'ai-quiz-master-language';

const dictionaries: Record<Language, Record<string, string>> = {
  ar: {
    'app.loading': 'جاري التحميل...',
    'common.cancel': 'إلغاء',
    'common.confirm': 'تأكيد',
    'common.back': 'رجوع',
    'common.close': 'إغلاق',
    'common.language': 'اللغة',
    'common.arabic': 'العربية',
    'common.english': 'English',
    'nav.home': 'الرئيسية',
    'nav.quizBuilder': 'إنشاء كويز',
    'nav.myQuizzes': 'اختباراتي',
    'nav.mindMaps': 'الخرائط الذهنية',
    'nav.tasks': 'المهام',
    'nav.history': 'السجل',
    'nav.profile': 'الملف الشخصي',
    'nav.admin': 'الإدارة',
    'auth.signIn': 'تسجيل الدخول',
    'auth.signingIn': 'جاري الدخول...',
    'auth.login': 'دخول',
    'auth.logout': 'تسجيل الخروج',
    'theme.light': 'تفعيل الوضع الفاتح',
    'theme.dark': 'تفعيل الوضع الداكن',
    'progress.saved': 'لديك اختبار غير مكتمل. تم حفظ {answered} من {total} إجابة.',
    'progress.resume': 'استكمال الاختبار',
    'footer.contact': 'للتواصل:',
    'footer.prayer': 'متنساش تصلّي على النبي',
    'quiz.exitTitle': 'الخروج من الكويز؟',
    'quiz.exitMessage': 'هل تريد الخروج قبل إتمام الكويز؟ لن يتم حفظ تقدمك.',
    'quiz.stay': 'البقاء',
    'quiz.exit': 'الخروج',
    'quiz.questionCount': 'السؤال {current} من {total}',
    'quiz.noQuestions': 'عذراً، لم يتم العثور على أسئلة لهذا الكويز.',
    'quiz.backToLibrary': 'العودة للمكتبة',
    'quiz.result': 'نتيجة الامتحان',
    'quiz.restartExam': 'إعادة الامتحان',
    'quiz.backHome': 'العودة للرئيسية',
    'quiz.yourAnswer': 'إجابتك:',
    'quiz.noAnswer': 'بدون إجابة',
    'quiz.correctAnswer': 'الإجابة الصحيحة:',
    'quiz.unavailableTitle': 'تعذر عرض هذا السؤال',
    'quiz.unavailableMessage': 'يبدو أن بيانات الكويز غير مكتملة أو تغيرت أثناء الامتحان.',
    'quiz.retry': 'إعادة المحاولة',
    'quiz.markReview': 'تعليم السؤال للمراجعة (M)',
    'quiz.shortAnswerHint': 'الأسئلة ذات الإجابة القصيرة لا تتأثر بحالة الأحرف (كبيرة/صغيرة).',
    'quiz.submitAnswer': 'إرسال الإجابة',
    'quiz.correct': 'إجابة صحيحة',
    'quiz.wrong': 'إجابة خاطئة. الإجابة الصحيحة: {answer}',
    'quiz.notSpecified': 'غير محددة',
    'quiz.explain': 'اشرح لي ليه',
    'quiz.previous': 'السابق',
    'quiz.next': 'التالي',
    'quiz.finish': 'إنهاء الكويز',
    'quiz.pause': 'إيقاف مؤقت',
    'quiz.resumeTime': 'استئناف الوقت',
    'quiz.previousMistake': 'أخطأت في هذا السؤال في آخر محاولة',
    'quiz.previousMistakeShort': 'أخطأت فيه سابقًا',
    'quiz.reviewTitle': 'مراجعة الأخطاء - {title}',
    'focus.title': 'صوتياتي',
    'focus.tooltip': 'وضع التركيز',
    'focus.nowPlaying': 'جاري التشغيل',
    'focus.quietSounds': 'أصوات هادئة',
    'focus.rain': 'صوت المطر',
    'focus.nature': 'أصوات الطبيعة',
    'focus.quran': 'القرآن الكريم (114 سورة)',
    'focus.searchSurah': 'ابحث عن سورة...',
    'focus.uploaded': 'ملفاتك المرفوعة',
    'focus.upload': 'ارفع ملف صوتي خاص بك',
    'focus.playError': 'فشل تشغيل الملف الصوتي',
    'focus.loadError': 'فشل تحميل أو تشغيل الملف الصوتي',
    'welcome.title': 'أهلاً بك يا {name}!',
    'welcome.heroName': 'بطل',
    'welcome.message': 'سعداء جداً بانضمامك إلينا في رحلة التعلم الذكي.',
    'welcome.prayer': 'صل على النبي بقا',
    'welcome.start': 'ابدأ رحلتك الآن',
    'welcome.created': 'تم إنشاء حسابك بنجاح',
    'home.hero.line1': 'حوّل محتواك',
    'home.hero.line2Prefix': 'إلى',
    'home.hero.line2Highlight': 'اختبارات تفاعلية',
    'home.hero.subtitle': 'أذكى أداة للطلاب والمعلمين. ارفع أي ملف ودع الذكاء الاصطناعي ينشئ اختبارًا احترافيًا أو خرائط ذهنية بكلمات قليلة.',
    'home.action.createQuiz': 'أنشئ اختبارًا',
    'home.action.getStartedFree': 'ابدأ مجانًا',
    'home.action.browseQuizzes': 'تصفح الاختبارات',
    'home.action.getStarted': 'ابدأ الآن',
    'home.action.buildMindMap': 'أنشئ خريطة ذهنية',
    'home.features.title': 'كل ما تحتاجه في مكان واحد',
    'home.features.subtitle': 'ثلاث أدوات ذكية قوية لتطوير تجربة التعلم',
    'home.feature.quiz.title': 'منشئ اختبارات بالذكاء الاصطناعي',
    'home.feature.quiz.description': 'ارفع PDF أو Word أو صورة ودع الذكاء الاصطناعي يحلل المحتوى وينشئ أسئلة احترافية في ثوان.',
    'home.feature.mindmap.title': 'منشئ الخرائط الذهنية',
    'home.feature.mindmap.description': 'أنشئ خرائط ذهنية تفاعلية بالذكاء الاصطناعي من أي موضوع، مع عرض شعاعي جميل وتحكم في التكبير والتحريك.',
    'home.feature.library.title': 'مكتبة الاختبارات',
    'home.feature.library.description': 'تصفح واختبر نفسك وتابع نتائجك. كل اختباراتك في مكان واحد مع إحصائيات أداء واضحة.',
    'home.how.title': 'كيف يعمل؟',
    'home.how.subtitle': 'ثلاث خطوات بسيطة لإنشاء اختبار احترافي',
    'home.step.upload.title': 'ارفع المحتوى',
    'home.step.upload.description': 'ارفع PDF أو Word أو صورة، أو الصق النص مباشرة في المحرر.',
    'home.step.ai.title': 'الذكاء الاصطناعي يحلل',
    'home.step.ai.description': 'يقرأ الذكاء الاصطناعي المحتوى وينشئ أسئلة دقيقة ومتنوعة تلقائيًا.',
    'home.step.share.title': 'ابدأ وشارك',
    'home.step.share.description': 'ابدأ الاختبار فورًا، تابع نتيجتك، وشاركه مع أي شخص.',
    'home.more.title': 'مميزات أكثر',
    'home.capability.multilingual.label': 'متعدد اللغات',
    'home.capability.multilingual.desc': 'يدعم العربية والإنجليزية وأكثر من 50 لغة أخرى',
    'home.capability.csv.label': 'استيراد CSV',
    'home.capability.csv.desc': 'استورد عددًا كبيرًا من الأسئلة من ملف CSV بسيط',
    'home.capability.fast.label': 'سريع وذكي',
    'home.capability.fast.desc': 'ينشئ اختبارًا كاملًا في أقل من 30 ثانية',
    'home.capability.free.label': 'ابدأ مجانًا',
    'home.capability.free.desc': 'أنشئ اختبارات بخطة مجانية سخية، وطورها فقط عند الحاجة',
    'home.seo.title': 'صانع اختبارات وخرائط ذهنية للطلاب والمعلمين',
    'home.seo.description': 'استخدم AI Quiz Master لإنشاء اختبارات تعليمية من الملفات والنصوص، وتنظيم المذاكرة، ومشاركة الامتحانات بسهولة من أي جهاز.',
    'home.seo.topic1.title': 'صانع اختبارات بالذكاء الاصطناعي',
    'home.seo.topic1.text': 'AI Quiz Master يساعدك على تحويل الدروس والملخصات والمحتوى التعليمي إلى كويزات منظمة تحتوي على أسئلة اختيار من متعدد، صح وخطأ، وأسئلة قصيرة.',
    'home.seo.topic2.title': 'إنشاء أسئلة من PDF وWord',
    'home.seo.topic2.text': 'يمكنك رفع ملفات PDF أو Word أو PowerPoint أو الصور، ثم استخراج الأفكار المهمة وتحويلها إلى اختبار جاهز للمراجعة أو المشاركة مع الطلاب.',
    'home.seo.topic3.title': 'خرائط ذهنية للمذاكرة',
    'home.seo.topic3.text': 'أنشئ خريطة ذهنية من أي موضوع لتلخيص المفاهيم والعلاقات بينها، وهي مفيدة للطلاب والمعلمين قبل الامتحانات أو أثناء شرح الدروس.',
    'home.seo.topic4.title': 'مشاركة امتحان بدون تسجيل دخول',
    'home.seo.topic4.text': 'بعد إنشاء الكويز يمكنك مشاركة رابط امتحان عام مع أي شخص، ويستطيع فتحه مباشرة من المتصفح دون الحاجة إلى إنشاء حساب.',
    'home.seo.banner.title': 'مناسب للمراجعة، التدريب، والاختبارات السريعة',
    'home.seo.banner.text': 'سواء كنت طالبًا يريد مراجعة درس، أو معلمًا يريد إنشاء امتحان سريع، أو صانع محتوى تعليمي يريد تحويل الشرح إلى أسئلة، يوفر لك التطبيق تجربة بسيطة لإنشاء كويز ومشاركته.',
    'home.cta.title': 'جاهز تطور طريقة تعلمك؟',
    'home.cta.subtitle': 'انضم الآن وابدأ إنشاء اختبارات وخرائط ذهنية ذكية من أي محتوى تعليمي',
    'home.stat.languages': 'لغة',
    'home.stat.generate': 'لإنشاء اختبار',
    'home.stat.free': 'للبداية',
  },
  en: {
    'app.loading': 'Loading...',
    'common.cancel': 'Cancel',
    'common.confirm': 'Confirm',
    'common.back': 'Back',
    'common.close': 'Close',
    'common.language': 'Language',
    'common.arabic': 'Arabic',
    'common.english': 'English',
    'nav.home': 'Home',
    'nav.quizBuilder': 'Quiz Builder',
    'nav.myQuizzes': 'My Quizzes',
    'nav.mindMaps': 'Mind Maps',
    'nav.tasks': 'Tasks',
    'nav.history': 'History',
    'nav.profile': 'Profile',
    'nav.admin': 'Admin',
    'auth.signIn': 'Sign In',
    'auth.signingIn': 'Signing in...',
    'auth.login': 'Login',
    'auth.logout': 'Logout',
    'theme.light': 'Switch to Light Mode',
    'theme.dark': 'Switch to Dark Mode',
    'progress.saved': 'You have an unfinished quiz. {answered} of {total} answers were saved.',
    'progress.resume': 'Resume quiz',
    'footer.contact': 'Contact:',
    'footer.prayer': 'متنساش تصلّي على النبي',
    'quiz.exitTitle': 'Exit quiz?',
    'quiz.exitMessage': 'Do you want to leave before finishing the quiz? Your progress will not be saved.',
    'quiz.stay': 'Stay',
    'quiz.exit': 'Exit',
    'quiz.questionCount': 'Question {current} of {total}',
    'quiz.noQuestions': 'Sorry, no questions were found for this quiz.',
    'quiz.backToLibrary': 'Back to library',
    'quiz.result': 'Exam result',
    'quiz.restartExam': 'Restart exam',
    'quiz.backHome': 'Back home',
    'quiz.yourAnswer': 'Your answer:',
    'quiz.noAnswer': 'No answer',
    'quiz.correctAnswer': 'Correct answer:',
    'quiz.unavailableTitle': 'This question cannot be displayed',
    'quiz.unavailableMessage': 'The quiz data looks incomplete or changed during the exam.',
    'quiz.retry': 'Try again',
    'quiz.markReview': 'Mark question for review (M)',
    'quiz.shortAnswerHint': 'Short-answer questions are not case-sensitive.',
    'quiz.submitAnswer': 'Submit answer',
    'quiz.correct': 'Correct answer',
    'quiz.wrong': 'Wrong answer. Correct answer: {answer}',
    'quiz.notSpecified': 'Not specified',
    'quiz.explain': 'Explain why',
    'quiz.previous': 'Previous',
    'quiz.next': 'Next',
    'quiz.finish': 'Finish quiz',
    'quiz.pause': 'Pause timer',
    'quiz.resumeTime': 'Resume timer',
    'quiz.previousMistake': 'You missed this question in your last attempt',
    'quiz.previousMistakeShort': 'Missed previously',
    'quiz.reviewTitle': 'Mistake review - {title}',
    'focus.title': 'My audio',
    'focus.tooltip': 'Focus mode',
    'focus.nowPlaying': 'Now playing',
    'focus.quietSounds': 'Quiet sounds',
    'focus.rain': 'Rain sound',
    'focus.nature': 'Nature sounds',
    'focus.quran': 'Quran (114 surahs)',
    'focus.searchSurah': 'Search for a surah...',
    'focus.uploaded': 'Uploaded files',
    'focus.upload': 'Upload your own audio file',
    'focus.playError': 'Audio playback failed',
    'focus.loadError': 'Audio loading or playback failed',
    'welcome.title': 'Welcome, {name}!',
    'welcome.heroName': 'hero',
    'welcome.message': 'We are happy to have you with us on this smart learning journey.',
    'welcome.prayer': 'صل على النبي بقا',
    'welcome.start': 'Start your journey',
    'welcome.created': 'Your account was created successfully',
    'home.hero.line1': 'Transform Your Content',
    'home.hero.line2Prefix': 'into',
    'home.hero.line2Highlight': 'Interactive Quizzes',
    'home.hero.subtitle': 'The smartest tool for students and teachers. Upload any file and let AI instantly generate a professional quiz or build mind maps with just a few words.',
    'home.action.createQuiz': 'Create a Quiz',
    'home.action.getStartedFree': 'Get Started Free',
    'home.action.browseQuizzes': 'Browse Quizzes',
    'home.action.getStarted': 'Get Started',
    'home.action.buildMindMap': 'Build a Mind Map',
    'home.features.title': 'Everything You Need in One Place',
    'home.features.subtitle': 'Three powerful AI-driven tools to supercharge your learning experience',
    'home.feature.quiz.title': 'AI Quiz Builder',
    'home.feature.quiz.description': 'Upload a PDF, Word doc, or image and let AI analyze the content and generate professional quiz questions in seconds.',
    'home.feature.mindmap.title': 'Mind Map Builder',
    'home.feature.mindmap.description': 'Generate interactive AI-powered mind maps from any topic. Beautiful radial SVG visuals with zoom and pan support.',
    'home.feature.library.title': 'Quiz Library',
    'home.feature.library.description': 'Browse, play, and track your results. All your quizzes in one place with detailed performance statistics.',
    'home.how.title': 'How It Works',
    'home.how.subtitle': 'Three simple steps to create a professional quiz',
    'home.step.upload.title': 'Upload Content',
    'home.step.upload.description': 'Upload a PDF, Word doc, or image, or paste text directly into the editor.',
    'home.step.ai.title': 'AI Analyzes',
    'home.step.ai.description': 'AI reads your content and generates accurate, varied questions automatically.',
    'home.step.share.title': 'Play & Share',
    'home.step.share.description': 'Start your quiz instantly, track your score, and share it with anyone.',
    'home.more.title': 'More Features',
    'home.capability.multilingual.label': 'Multilingual',
    'home.capability.multilingual.desc': 'Supports Arabic, English, and 50+ other languages',
    'home.capability.csv.label': 'CSV Import',
    'home.capability.csv.desc': 'Import bulk questions from a simple CSV file',
    'home.capability.fast.label': 'Fast & Smart',
    'home.capability.fast.desc': 'Generates a full quiz in under 30 seconds',
    'home.capability.free.label': 'Free to Start',
    'home.capability.free.desc': 'Create quizzes with a generous free plan and upgrade only when you need more',
    'home.seo.title': 'Quiz and Mind Map Builder for Students and Teachers',
    'home.seo.description': 'Use AI Quiz Master to create educational quizzes from files and text, organize studying, and share exams easily from any device.',
    'home.seo.topic1.title': 'AI Quiz Builder',
    'home.seo.topic1.text': 'AI Quiz Master helps you turn lessons, summaries, and educational content into organized quizzes with multiple choice, true or false, and short-answer questions.',
    'home.seo.topic2.title': 'Create Questions from PDF and Word',
    'home.seo.topic2.text': 'Upload PDF, Word, PowerPoint, or image files, then extract the important ideas and turn them into a ready quiz for review or sharing with students.',
    'home.seo.topic3.title': 'Mind Maps for Studying',
    'home.seo.topic3.text': 'Create a mind map from any topic to summarize concepts and relationships, useful for students and teachers before exams or during lessons.',
    'home.seo.topic4.title': 'Share an Exam Without Login',
    'home.seo.topic4.text': 'After creating a quiz, you can share a public exam link with anyone, and they can open it directly in the browser without creating an account.',
    'home.seo.banner.title': 'Great for review, practice, and quick exams',
    'home.seo.banner.text': 'Whether you are a student reviewing a lesson, a teacher creating a quick exam, or an educational creator turning explanations into questions, the app gives you a simple way to create and share quizzes.',
    'home.cta.title': 'Ready to Level Up Your Learning?',
    'home.cta.subtitle': 'Join now and start creating smart quizzes and mind maps from any educational content',
    'home.stat.languages': 'Languages',
    'home.stat.generate': 'To Generate a Quiz',
    'home.stat.free': 'To Start',
  },
};

const LanguageContext = createContext<LanguageContextValue | null>(null);

const getInitialLanguage = (): Language => {
  if (typeof window === 'undefined') return 'ar';
  const saved = localStorage.getItem(STORAGE_KEY);
  return saved === 'en' || saved === 'ar' ? saved : 'ar';
};

const interpolate = (text: string, values?: Record<string, string | number>) => {
  if (!values) return text;
  return Object.entries(values).reduce(
    (result, [key, value]) => result.replaceAll(`{${key}}`, String(value)),
    text
  );
};

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguageState] = useState<Language>(getInitialLanguage);
  const direction = language === 'ar' ? 'rtl' : 'ltr';

  useEffect(() => {
    localStorage.setItem(STORAGE_KEY, language);
    document.documentElement.lang = language;
    document.documentElement.dir = direction;
  }, [direction, language]);

  const value = useMemo<LanguageContextValue>(() => ({
    language,
    direction,
    setLanguage: setLanguageState,
    toggleLanguage: () => setLanguageState(current => current === 'ar' ? 'en' : 'ar'),
    t: (key, values) => interpolate(dictionaries[language][key] || key, values),
  }), [direction, language]);

  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>;
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used inside LanguageProvider');
  }
  return context;
};
